### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by glensc** [tedconf/fessonia#33]
I'm writing my application in TypeScript and would like to see TypeScript typing support.

**Comment by nihonjinrxs** [comment]
Hi, @glensc. I'm not opposed to adding this here in a `types` folder or something (whatever the convention is for this -- I'm not sure).

That said, we're not using TypeScript at all, and I don't want to add a TypeScript dependency to the project. I also don't know much TypeScript, so this is likely to take a lot of effort and mean a lot of learning on my part, which in turn means this won't get done soon.

As an alternative, I'm happy to accept pull requests for this if you have time to do that. I only ask that the pull request be limited to the type definition files themselves, and not include new build steps or TypeScript tooling added to the library development setup. Thanks!

**Comment by glensc** [comment]
I think in such cases the types get submitted to https://github.com/DefinitelyTyped/DefinitelyTyped

But I personally think it's better if they are in project itself, where the code is.

also, I have never created any typing, so a lot of effort my side too.

**Comment by nihonjinrxs** [comment]
Seems like this may now be able to be achieved [via the Microsoft TypeScript compiler](https://www.typescriptlang.org/tsconfig#emitDeclarationOnly) [using the JSdoc comments](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html). Requires some experimentation and research.

Hat tip to @redoPop for pointing this out.

**Comment by nihonjinrxs** [comment]
Found a guide for doing this here: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

Will submit a PR shortly. @glensc appreciate a look once that's up to see if this would suit your needs.

**Comment by universalhandle** [comment]
Hello, I commented on #41 saying I'm happy to help with adding type definitions to this repository.

I'm using this library for the first time, so I'm not as familiar with it as others will be, and I'm not sure how typical my usage is, so I'll have questions about how this library is intended to be used which will inform how I define the types. I've put my questions/comments in this thread since they pertain to the general matter of TypeScript support and not the specifics of that pull request.

While I've managed to do enough typing to get my project to work, for the purposes of generally distributed type definitions I think it would be useful for the project maintainers/stakeholders to help me make some decisions:

### Should the type definitions describe what a developer _could_ do or _should_ do?
In other words, should they promote best practices for using fessonia, or should they be informed by a [strict constructionist](https://en.wikipedia.org/wiki/Strict_constructionism) (not a technical term) point of view, communicating the shape of the JavaScript code as literally and precisely as possible?

To put this into context, consider `FFmpegOption._loadFilterGraph`. It's marked `@private` and the leading underscore would suggest the same, but, technically, this method could be called from anywhere. I'm inclined not to expose this interface in the type definition (i.e., I'm inclined to "promote best practices" vs. take a strict constructionist approach), but I can imagine there are arguments for doing it the other way. I'm inclined to treat the class's `validate` method the same way.

Likewise, the constructor defines some members that are publicly accessible (`name`, `optionName`, `arg`), but as far as I can tell, these are intended to be used inside the class only. "Advertising" their existence to TypeScript developers may encourage direct manipulation of their values, which perhaps we don't want to promote.

Of course, this begs the question of whether downstream devs should be directly interacting with `FFmpegOption` objects at all. The file-level comments suggest the class is for internal use only, but some amount of type definition might be necessary in order to type parameters for other methods which eventually feed into its constructor. So, without further ado, my second major question:

### What are the primary interfaces a downstream developer should use for this library?
Should developers import only `index.js`, call `getFessonia`, and interact only with that function's return, or are they ever expected/encouraged to directly import the classes represented in the return (or anything else)?

### Fin
Thanks for bearing with my lengthy comment. Other questions may arise, but hearing some thoughts around these two will help me continue to make progress. Thanks!

**Comment by glensc** [comment]
@universalhandle in my project, which does video segmenting/encoding/concat, I'm only using these three exports:

```typescript
import getFessonia from "@tedconf/fessonia";

const fessonia = getFessonia({
  debug: true,
  log_warnings: true
});

export const { FFmpegCommand, FFmpegInput, FFmpegOutput } = fessonia;
```

hope this helps!

**Comment by nihonjinrxs** [comment]
Hi, @glensc and @universalhandle. Thanks so much for the attention to this and for the effort you've already put in. We've been on holiday, so I'm just getting the chance to take a look. Give me a bit to review all that's here, and I'll respond by end of day Monday.
